version: "3.9"

services:
  library-mamagement-system-nginx:
    image: 'nginx:stable-alpine'
    container_name: library-mamagement-system-nginx
    ports:
      - '8001:80'
    volumes:
      - ./:/var/www/html
      - ./docker-configs/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
  library-mamagement-system-mysql:
    image: mysql:8.0.24
    user: "${UID}:${GID}"
    container_name: library-mamagement-system-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306
    volumes:
      - ./docker-configs/mysql:/var/lib/mysql/
  phpmyadmin:
    depends_on:
      - library-mamagement-system-mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8002:80
    environment:
      PMA_HOST: library-mamagement-system-mysql
      MYSQL_ROOT_PASSWORD: root
  library-mamagement-system-app:
    build:
      context: .
      dockerfile: app.dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
    container_name: library-mamagement-system-app
    volumes:
      - ./:/var/www/html
  library-mamagement-system-mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'
    ports:
      - 1025:1025 # smtp server
      - 8003:8025 # web ui
